# **NUMPY**

Trabajar con arrays

In [86]:
import numpy as np

x = np.array([[1,2,4,6],[5,2,6,9]])
print(f"{x} -- {type(x)}")
print(x.ndim)           #Nivel de dimensión 
print(x.shape)          #Altura por anchura
print(x.dtype)          #Tipo de datos
x = x.astype(float)     #Parseo de los datos
print(x.dtype)
print(x.size)           #Tamaño total
x = np.resize(x,[8,1])  #Cambia el tamaño
x.shape=([4,2])         #Cambia el tamaño
print(x)

[[1 2 4 6]
 [5 2 6 9]] -- <class 'numpy.ndarray'>
2
(2, 4)
int32
float64
8
[[1. 2.]
 [4. 6.]
 [5. 2.]
 [6. 9.]]


In [87]:
y = np.zeros((5,2))     #Generación de arrays de 0s
print(y)
print("##################")
y = np.eye(3)           #Matriz de identidad
print(y)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
##################
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [88]:
x = np.arange(2,6,0.5,dtype=float) #Hace un array partiendo de x valor com suma de 0.5 6 cifras
x

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [89]:
x = np.linspace(2,7, 10) #A partir de un valor inicial y final rellena 10 numeros intermedios para llegar al resultado
print(x)

[2.         2.55555556 3.11111111 3.66666667 4.22222222 4.77777778
 5.33333333 5.88888889 6.44444444 7.        ]


In [90]:
np.random.seed(42)      #Inicializar generador 42 por el sentido de la vida xd
x = np.random.randint(2,8)  #Random de números entre x e Y
x = np.random.random(9)     #Genera nueve valores random entre 0-1
x = np.random.uniform(10,20, size=10) #Entre 10 y 20 de 10 tamaño
x = np.random.normal(10,20, size=10) #Genera un array que da de media 20 con 10 elementos
x = np.random.choice(["cara", "cruz"], size = 10) #Elige 10 veces entre esos dos
x = np.random.choice([0, 1], size = 10,p=[0.7,0.3]) #Entre 0 y 1 con probabilidades
x = np.nan
x = np.inf
x 

inf

In [93]:
x = np.array(range(9)).reshape((3,3))   #Crea un array hasta 9 de 3-3
print(x)
x[0:2, 1]               #Lonchea el array
x[:, 1:3]               #Lonchea empezando por el 1 y 3 sin contar
x[[2,1], [2,2]]         #De la fila 2 coge el elemento 2 luego de la fila 1 coge el elemento 2 teniendo en cuenta que se empieza en el 0
x[[1,2, 0], [1,1, 1]]   #Lo mismo

x[1:3, 0:3] = [[11], [11]]  #Subsituye los valores de cordenadas por 11s
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [11 11 11]
 [11 11 11]]


In [104]:
print(x >3)     #Dice cuales de los valores son mayores de 3 y hace un array booleano (SELECCIÓN BOOLEANA)
x[x>3]          #Hace un array de valores > 3
b = (x > 2)
b = np.logical_not(b)   #Da la vuelta a los booleanos
b

[[False False False]
 [False  True  True]
 [ True  True  True]]


array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [107]:
x = np.array(range(9)).reshape((3,3))
print(x)
x=x+5
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [112]:
x = np.full(fill_value=True,shape=(3,3))    #3x3 De Trues
x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [115]:
x=np.arange(10)     #Printar pares
x[x%2==0]

array([0, 2, 4, 6, 8])

In [116]:
x[x%2!=0]=-1        #Remplazar impares
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [125]:
x = np.arange(10).reshape((-1,5))
print(x)
print(np.sum(x,axis=0))
x = np.arange(10).reshape((-1,5))
print(np.sum(x,axis=1,keepdims=True))       #KeepDims mantiene forma

[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 5  7  9 11 13]
[[10]
 [35]]


In [134]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(a == b)
np.where((b > 5) & (b < 10))

[False  True False  True False  True False  True False False]


(array([0, 4, 6, 8, 9], dtype=int64),)

In [136]:
arr = np.arange(9).reshape(3,3)
arr[:,[2,1,0]]                 # : Significa todas las filas

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [151]:
np.random.uniform(5,10,size=(5,3))

array([[9.53783237, 6.24646115, 7.05191462],
       [8.77775569, 6.14399083, 5.38489955],
       [6.44875726, 5.80610644, 9.64848826],
       [9.0406019 , 8.16701878, 9.35730295],
       [9.01836038, 5.93285029, 9.46279499]])